const shirts = [
  {
    id: 1,
    name: "Void",
    image_front: "https://i.imgur.com/GtO8VPx.png",
    image_back: "",
    color: "white",
    price: "$45",
    charity: "10% to Union of Concerned Scientists",
    artist: "Primal Butter",
    route_name: "void-white",
    description: [
      "melt into the void",
      "it stares back at you 😵‍💫",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 2,
    name: "Void",
    image_front: "https://i.imgur.com/yMr5EgV.png",
    image_back: "",
    color: "black",
    price: "$45",
    charity: "10% to 10% to Union of Concerned Scientists",
    artist: "Primal Butter",
    route_name: "void-black",
    description: [
      "melt into the void",
      "it stares back at you 😵‍💫",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 3,
    name: "BLM - George Floyd",
    image_front: "https://i.imgur.com/myGXDo8.png",
    image_back: "https://i.imgur.com/Jq12sMO.png",
    color: "black",
    price: "$55",
    charity:
      "100% to Act Blue - Anti Police Brutality Fund and Racial Justice Fund",
    artist: "Primal Butter",
    route_name: "blm-floyd-black",
    description: [
      "stand for equity and equality",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 4,
    name: "BLM - George Floyd",
    image_front: "https://i.imgur.com/L0RL5KQ.png",
    image_back: "https://i.imgur.com/biB6U1b.png",
    color: "white",
    price: "$55",
    charity:
      "100% to Act Blue - Anti Police Brutality Fund and Racial Justice Fund",
    artist: "Primal Butter",
    route_name: "blm-floyd-white",
    description: [
      "stand for equity and equality",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 5,
    name: "BLM - USA",
    image_front: "https://i.imgur.com/myGXDo8.png",
    image_back: "https://i.imgur.com/wfNVbTl.png",
    color: "black",
    price: "$55",
    charity:
      "100% to Act Blue - Anti Police Brutality Fund and Racial Justice Fund",
    artist: "Primal Butter",
    route_name: "blm-usa-black",
    description: [],
    description: [
      "stand for equity and equality",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 6,
    name: "BLM - USA",
    image_front: "https://i.imgur.com/L0RL5KQ.png",
    image_back: "https://i.imgur.com/idf4ulE.png",
    color: "white",
    price: "$55",
    charity:
      "100% to Act Blue - Anti Police Brutality Fund and Racial Justice Fund",
    artist: "Primal Butter",
    route_name: "blm-usa-white",
    description: [
      "stand for equity and equality",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 7,
    name: "Medusa",
    image_front: "https://i.imgur.com/ijUgRpv.png",
    image_back: "",
    color: "white",
    price: "$45",
    charity: "10% to Partnership Against Domestic Violence",
    artist: "Culture Closet",
    route_name: "medusa-white",
    description: ["", "100% Organic Cotton", "Made in USA"],
  },
  {
    id: 8,
    name: "Medusa",
    image_front: "https://i.imgur.com/S0hYfYP.png",
    image_back: "",
    color: "black",
    price: "$45",
    charity: "10% to Partnership Against Domestic Violence",
    artist: "Culture Closet",
    route_name: "medusa-black",
    description: ["", "100% Organic Cotton", "Made in USA"],
  },
  {
    id: 9,
    name: "Skulls",
    image_front: "https://i.imgur.com/C5yQBG2.png",
    image_back: "",
    color: "white",
    price: "$40",
    charity: "10% to Partnership Against Domestic Violence",
    artist: "Culture Closet",
    route_name: "skulls-white",
    description: ["", "100% Organic Cotton", "Made in USA"],
  },
  {
    id: 10,
    name: "Skulls",
    image_front: "https://i.imgur.com/fX8CyFE.png",
    image_back: "",
    color: "black",
    price: "$40",
    charity: "10% to Partnership Against Domestic Violence",
    artist: "Culture Closet",
    route_name: "skulls-black",
    description: ["", "100% Organic Cotton", "Made in USA"],
  },
  {
    id: 11,
    name: "Vibing Test Tube",
    image_front: "https://i.imgur.com/AvW2uqw.png",
    image_back: "",
    color: "black",
    price: "$45",
    charity: "10% to Last Prisoner Project",
    artist: "Chems'n'Vibes",
    route_name: "test-tube-black",
    description: [
      "take some chems, feel some vibes",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 12,
    name: "Vibing Test Tube",
    image_front: "https://i.imgur.com/FJJBMEC.png",
    image_back: "",
    color: "white",
    price: "$45",
    charity: "10% to Last Prisoner Project",
    artist: "Chems'n'Vibes",
    route_name: "test-tube-white",
    description: [
      "take some chems, feel some vibes",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 13,
    name: "civilian.",
    image_front: "https://i.imgur.com/VYprw1s.png",
    image_back: "",
    color: "black",
    price: "$40",
    charity: "10% to Red Cross",
    artist: "trèscray",
    route_name: "civilian-black",
    description: [
      "civilians make up the world",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 14,
    name: "civilian.",
    image_front: "https://i.imgur.com/VmSOUiS.png",
    image_back: "",
    color: "white",
    price: "$40",
    charity: "10% to Red Cross",
    artist: "trèscray",
    route_name: "civilian-white",
    description: [
      "civilians make up the world",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 15,
    name: "psychotic.",
    image_front: "https://i.imgur.com/PojoIfk.png",
    image_back: "",
    color: "black",
    price: "$40",
    charity: "10% to Jed Foundation",
    artist: "trèscray",
    route_name: "psychotic-black",
    description: [
      "kinda good looking, kinda crazy",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 16,
    name: "psychotic.",
    image_front: "https://i.imgur.com/GeCeaJ8.png",
    image_back: "",
    color: "white",
    price: "$40",
    charity: "10% to Jed Foundation",
    artist: "trèscray",
    route_name: "psychotic-white",
    description: [
      "kinda good looking, kinda crazy",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 17,
    name: "грустная сука (sad bitch)",
    image_front: "https://i.imgur.com/rx2xkmf.png",
    image_back: "",
    color: "black",
    price: "$45",
    charity: "10% to Trevor Project",
    artist: "hex",
    route_name: "sad-bitch-black",
    description: [
      "just a tad bit on the inside 🤡",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 18,
    name: "грустная сука (sad bitch)",
    image_front: "https://i.imgur.com/7hFfeMN.png",
    image_back: "",
    color: "white",
    price: "$45",
    charity: "10% to Trevor Project",
    artist: "hex",
    route_name: "sad-bitch-white",
    description: [
      "just a tad bit on the inside 🤡",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 19,
    name: "disorder",
    image_front: "https://i.imgur.com/X6JbTAv.png",
    image_back: "",
    color: "black",
    price: "$40",
    charity: "10% to Waterkeeper Alliance",
    artist: "hex",
    route_name: "disorder-black",
    description: [
      "just a tad bit on the inside 🤡",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
  {
    id: 20,
    name: "disorder",
    image_front: "https://i.imgur.com/5kd5T8K.png",
    image_back: "",
    color: "white",
    price: "$40",
    charity: "10% to Waterkeeper Alliance",
    artist: "hex",
    route_name: "disorder-white",
    description: [
      "just a tad bit on the inside 🤡",
      "100% Organic Cotton",
      "Made in USA",
    ],
  },
];

module.exports = shirts;
